### ISSUE TITLE
Adding Credential

### ISSUE THREAD

**Issue by InvokerFury** [UpSync-Dev/docker-compose-mongo-replica-set#2]
Hi Sir,

can i add credential to this? could you guide please how to add username and password

thanks, 

regards

**Comment by ma3574** [comment]
What do you mean by adding credentials?

**Comment by sidzan** [comment]
How can you access the Database cluster? how to create credentaials? Could you please update the README.

**Comment by ma3574** [comment]
@sidzan I've merged in your PR  with one minor tweak to remove `localhost:27017` as it's not required

@InvokerFury As this is a very simple setup that starts all three nodes of the cluster on your development machine, I've omitted anything extra. This setup isn't a production setup and should not be used for anything like that. Having said that if you wish to add authentication to the cluster, I would recommend following the [authentication guides](https://docs.mongodb.com/manual/core/authentication/) for your version of Mongo on the official website.
