### ISSUE TITLE
connect with python

### ISSUE THREAD

**Issue by FarzanehGhorbani** [UpSync-Dev/docker-compose-mongo-replica-set#8]
Hello, thank you for this repository
I used this repository for create mongodb cluster, but I can't connect to it from Python. thank you

**Comment by ma3574** [comment]
Hi @FarzanehGhorbani 

It would be best to refer to Mongo documentation directly. E.g. See [here](https://www.mongodb.com/docs/atlas/tutorial/connect-to-your-cluster/) It is documentation for Mongo DB Atlas which is the hosted version provided by Mongo but you can use the instructions and then where it says:
```
client = MongoClient('<your updated connection string>')
```
you can use the connection string from the README:
```
client = MongoClient('mongodb://mongo1:30001,mongo2:30002,mongo3:30003/?replicaSet=my-replica-set')

```

Hope that helps.
